version: "3"
services:
  {{cookiecutter.service_name}}:
    container_name: {{cookiecutter.service_name }}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "{{cookiecutter.host_port}}:{{cookiecutter.container_port}}"